name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:     
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}} 
             
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      working-directory: EventBase
      run: dotnet restore
    - name: Build
      working-directory: EventBase
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: EventBase
      run: dotnet test --no-restore --verbosity normal
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: EventBase/EventBase.Client
        # NuGet package id, used for version detection & defaults to project name
        PACKAGE_NAME: Dinoroar.EventBase.Client
        VERSION_STATIC: 0.0.${{ steps.buildnumber.outputs.build_number }}
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{ secrets.GITHUB_TOKEN }}
        NUGET_SOURCE: https://nuget.pkg.github.com/DinoRoar/

    
